export * from './workspaces'
export * from './users'
export * from './companies'
export * from './contacts'
export * from './products'
export * from './deals'
export * from './documents'   // replaces notes — content lives in Supabase Storage
export * from './activities'
export * from './files'
export * from './pipeline'
export * from './chat'
export * from './auth'
export * from './pitch-decks'
export * from './customization-requests'
